### ISSUE TITLE
App Crash on Start

### ISSUE THREAD

**Issue by gthbusrr** [Ruddle/RemoteCam#17]
App Crash on Start
```
12-11 22:57:34.527 18686 18686 E AndroidRuntime: FATAL EXCEPTION: main
12-11 22:57:34.527 18686 18686 E AndroidRuntime: Process: com.samsung.android.scan3d, PID: 18686
12-11 22:57:34.527 18686 18686 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.samsung.android.scan3d.serv.Cam@a427085 with Intent { act=start_camera_engine cmp=com.samsung.android.scan3d/.serv.Cam }: java.lang.NullPointerException
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: Caused by: java.lang.NullPointerException
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at com.samsung.android.scan3d.serv.CamEngine.updateView(CamEngine.kt:310)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at com.samsung.android.scan3d.serv.CamEngine.initializeCamera(CamEngine.kt:296)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at com.samsung.android.scan3d.serv.CamEngine$initializeCamera$1.invokeSuspend(Unknown Source:14)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at com.samsung.android.scan3d.serv.Cam.onStartCommand(Cam.kt:98)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
12-11 22:57:34.527 18686 18686 E AndroidRuntime: 	... 9 more
```

Phone: Samsung Galaxy S22 Ultra
OS: Android 14

**Comment by PathosEthosLogos** [comment]
Same, base S23, Android 14
Unsure how to get crash log though

**Comment by fragtion** [comment]
Same here. Galaxy S22 Ultra Android 15. Crash on start (app freshly installed)

**Comment by FantasticGarbage** [comment]
Also on my galaxy A52s (Android 14). This seems to be a common issue on samsung devices for some reason.

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
Add me to the list.

**Device:** Sony Xperia 1V
**OS Ver:** Android 14

Found this fork which does work: https://github.com/alan7383/RemoteCam-Enhanced  
Use at your own risk, I ran [v1.0.2](https://github.com/alan7383/RemoteCam-Enhanced/releases/tag/1.0.2) through VirusTotal and it came back clean, but I'm not an expert.

**Comment by e1ke** [comment]
Same for me, Pixel 7a Android 16. Are there any plans on updating this app, @Ruddle ? I like the aspects, that your app is open source and supports OBS on the fly.

Huge thanks in advance!

**Comment by Shirakawa-Kotone** [comment]
+1, i met it on android 14
