### ISSUE TITLE
Crash on Pixel 7 upon startup

### ISSUE THREAD

**Issue by TheReiko69** [Ruddle/RemoteCam#7]
Whenever I open up the app I get this crash immediately on my pixel 7. I have tried both the Fdroid build, as well ae the github build posted on this repo and I get the same error.

````
type: crash
osVersion: google/panther/panther:13/TQ3A.230805.001/2023080800:user/release-keys
package: com.samsung.android.scan3d:4
process: com.samsung.android.scan3d
processUptime: 199 + 310 ms
installer: io.github.muntashirakon.AppManager

java.lang.RuntimeException: Unable to start service com.samsung.android.scan3d.serv.Cam@fc5514b with Intent { act=start_camera_engine cmp=com.samsung.android.scan3d/.serv.Cam }: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4690)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2186)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.NullPointerException
	at com.samsung.android.scan3d.serv.CamEngine.updateView(CamEngine.kt:310)
	at com.samsung.android.scan3d.serv.CamEngine.initializeCamera(CamEngine.kt:296)
	at com.samsung.android.scan3d.serv.CamEngine$initializeCamera$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.samsung.android.scan3d.serv.Cam.onStartCommand(Cam.kt:98)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4672)
	... 11 more

````

**Comment by adrianmmiller** [comment]
Same on Pixel 6 Pro

Instant FC.....won't even open.

Are you targeting libraries etc that only exist on Samsung devices?

**Comment by s0me0ne-unkn0wn** [comment]
Same here, Pixel 7 Pro.

**Comment by work-jokomanza** [comment]
Same here too, Pixel 6a

**Comment by austinharvey82** [comment]
same here on samsung

**Comment by kylianpl** [comment]
#13 fixed it for the Google Pixel 8 Pro
