### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by flt6** [Ruddle/RemoteCam#9]
Crashed on start on HUAWEI phone
I got this as the crash log:
```log
08-30 20:37:12.392 17700 17700 E AndroidRuntime: FATAL EXCEPTION: main
08-30 20:37:12.392 17700 17700 E AndroidRuntime: Process: com.samsung.android.scan3d, PID: 17700
08-30 20:37:12.392 17700 17700 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.samsung.android.scan3d.serv.Cam@3a2c271 with Intent { act=start_camera_engine cmp=com.samsung.android.scan3d/.serv.Cam }: java.lang.NullPointerException
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4971)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.app.ActivityThread.access$3300(ActivityThread.java:260)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2486)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
08-30 20:37:12.392 17700 17700 E AndroidRuntime: Caused by: java.lang.NullPointerException
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at com.samsung.android.scan3d.serv.CamEngine.updateView(CamEngine.kt:310)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at com.samsung.android.scan3d.serv.CamEngine.initializeCamera(CamEngine.kt:296)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at com.samsung.android.scan3d.serv.CamEngine$initializeCamera$1.invokeSuspend(Unknown Source:14)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at com.samsung.android.scan3d.serv.Cam.onStartCommand(Cam.kt:98)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4951)
08-30 20:37:12.392 17700 17700 E AndroidRuntime:        ... 8 more
```
And this log may help:
```log
08-30 20:34:46.531  1001  1528 E DE N ABT: mergeProcessorOperatingNormal:1523: COMPONENT_GMP already has data, can't add new data with MODE_COLOR_ENHANCE, mode:MODE_CAMERA|MODE_COLOR_ENHANCE|0x900->MODE_CAMERA|MODE_COLOR_ENHANCE|0x900
```

**Comment by flt6** [comment]
Whole log for the process:
```log
08-30 20:39:37.823 18340 18340 W .android.scan3: type=1400 audit(0.0:16677): avc: denied { read } for pid=18340 name="u:object_r:device_config_runtime_native_prop:s0" dev="tmpfs" ino=12907 scontext=u:r:untrusted_app:s0:c172,c256,c512,c768 tcontext=u:object_r:device_config_runtime_native_prop:s0 tclass=file permissive=0
08-30 20:39:37.823   663   663 D Zygote  : Forked child process 18340
08-30 20:39:37.826  1964  2043 I ActivityManager: Start proc 18340:com.samsung.android.scan3d/u0a172 for start application com.samsung.android.scan3d
08-30 20:39:37.831 18340 18340 E libc    : Access denied finding property "persist.device_config.runtime_native.use_app_image_startup_cache"
08-30 20:39:37.831 18340 18340 E .android.scan3: LoadAppImageStartupCache enabled : 1
08-30 20:39:37.833 18340 18340 I .android.scan3: Reinit property: dalvik.vm.checkjni= false
08-30 20:39:37.833 18340 18340 I .android.scan3: ReInitProperties: persist.vm.debug.dumpapi= false
08-30 20:39:37.835 18340 18340 E .android.scan3: Not starting debugger since process cannot load the jdwp agent.
08-30 20:39:37.844 18340 18340 D ActivityThread: Attach thread to application
08-30 20:39:37.850 18340 18359 I HwActivityThreadImpl: mSocketName: 972b33cb-d1b5-4e3c-990d-f5d5363ddb4e
08-30 20:39:37.850 18340 18359 I HwActivityThreadImpl: initPreloadedSocked end mPreloadStatus 2
08-30 20:39:37.857 18340 18360 I ActivityThread: Init compatible state: true
08-30 20:39:37.858 18340 18360 D HwFrameworkSecurityPartsFactory: HwFrameworkSecurityPartsFactory in.
08-30 20:39:37.858 18340 18360 I HwFrameworkSecurityPartsFactory: add HwFrameworkSecurityPartsFactory to memory.
08-30 20:39:37.858 18340 18360 D BehaviorCollectManager: hook process for AI virus second
08-30 20:39:37.858 18340 18360 I BehaviorCollectManager: bindAnalyzerService: huawei.android.security.IAppBehaviorDataAnalyzer$Stub$Proxy@f2115df pid:18340
08-30 20:39:37.866 18340 18340 D ApplicationLoaders: createClassLoader zip: /data/app/com.samsung.android.scan3d-Wzx642ertaYdpKAyYg73jw==/base.apk librarySearchPath: /data/app/com.samsung.android.scan3d-Wzx642ertaYdpKAyYg73jw==/lib/arm64 libraryPermittedPath: /data/user/0/com.samsung.android.scan3d parent: java.lang.BootClassLoader@4ba8039 targetSdkVersion: 33 isBundled: false classLoaderName: null sharedLibraries: null
08-30 20:39:37.883 18340 18340 I HwActivityThreadImpl: accept socket mSocketName: 972b33cb-d1b5-4e3c-990d-f5d5363ddb4e
08-30 20:39:37.883 18340 18360 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.samsung.android.scan3d#10172#256
08-30 20:39:37.883 18340 18360 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=0 newCnt=1
08-30 20:39:37.884 18340 18360 I HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=com.samsung.android.scan3d#10172#0
08-30 20:39:37.884 18340 18360 I HwApiCacheMangerEx: need clear apicache,because volumes changed,oldCnt=1 newCnt=1
08-30 20:39:37.918 18340 18361 I HwActivityThreadImpl: before connect app.socketName:972b33cb-d1b5-4e3c-990d-f5d5363ddb4e
08-30 20:39:37.918 18340 18340 I HwActivityThreadImpl: accept socket end
08-30 20:39:37.919 18340 18361 W HwActivityThreadImpl: closeStream error.
08-30 20:39:37.919 18340 18361 I HwActivityThreadImpl: connectContinuePreload end mPreloadStatus 3
08-30 20:39:37.919 18340 18340 W HwActivityThreadImpl: closeStream error.
08-30 20:39:37.919 18340 18340 I HwActivityThreadImpl: acceptPreloadedApplication end mPreloadStatus 3
08-30 20:39:37.923  1964  2036 D HwGameAssistantController: UPDATE: mCurFgPkg=com.samsung.android.scan3d, mCurFgPid=18340, mIsCurGame=false
08-30 20:39:37.924 18340 18360 I HwPartIawareFactory: add android.common.HwPartIawareFactoryImpl to memory.
08-30 20:39:37.925 18340 18360 I AwareBitmapCacher: init processName:com.samsung.android.scan3d pid=18340 uid=10172
08-30 20:39:37.927 18340 18373 E AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@35b628a
08-30 20:39:37.949  1964  2159 D HwActivityManagerServiceEx: notifyAppToTop pid:18340, enable:1
08-30 20:39:37.949 18340 18340 I HwTypeface: updateFont: scale=1.17
08-30 20:39:37.950 18340 18340 D SystemFonts: areFontsVariable: script=Hans
08-30 20:39:37.950 18340 18340 I ActivityThread: finishPreloaded preloadStatus 3
08-30 20:39:37.952  1964  2714 D ActivityManager: finishBindApplication callingPid 18340
08-30 20:39:37.952  1964  2714 D ActivityManager: finishBindApplication preloadStatus: 0 app: ProcessRecord{2ddcf05 18340:com.samsung.android.scan3d/u0a172} uidRec.isPreload: false
08-30 20:39:37.952 18340 18340 I ActivityThread: finishPreloaded end preloadStatus 3
08-30 20:39:37.952 18340 18340 W DisplayEventDispatcher: dispatcher 0x7018025f40 ~ ignoring unknown event type 0x736f6674
08-30 20:39:37.952 18340 18340 I RmeSchedManager: init Rme, version is: v1.0
08-30 20:39:37.952 18340 18340 I RmeSchedManager: init Rme, version is: v1.0
08-30 20:39:37.952 18340 18340 I RtgSchedEvent: current pid:18340 AppType:-1
08-30 20:39:37.953 18340 18340 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cf28518
08-30 20:39:37.956 18340 18340 D OpenGLRenderer: disableOutlineDraw is true
08-30 20:39:37.964 18340 18380 I OpenGLRenderer: RenderThread: progress name = [com.samsung.android.scan3d], viewCornerType = 0
08-30 20:39:37.965 18340 18382 I iGraphics: [0020080c] pn: com.samsung.android.scan3d, p: 18340
08-30 20:39:37.965 18340 18382 I iGraphics: [0030080c] no spt app: com.samsung.android.scan3d
08-30 20:39:37.966  1964  2714 V ActivityManager: Successfully start provider ContentProviderRecord{2929ff8 u0 com.android.providers.settings/.hwext.HwSettingsProvider} launchingApp=null caller pid= 18340
08-30 20:39:37.969 18340 18340 V ActivityThread: callActivityOnCreate
08-30 20:39:37.973 18340 18340 I CAMERAACTIVITY: CAMERAACTIVITY onCreate
08-30 20:39:37.987 18340 18340 I DecorView[]: pkgName:com.samsung.android.scan3d old windowMode:0 new windoMode:1, isFixedSize:false
08-30 20:39:37.996 18340 18340 D ActivityThread: add activity client record, r= ActivityRecord{abe55c1 token=android.os.BinderProxy@cf28518 {com.samsung.android.scan3d/com.samsung.android.scan3d.CameraActivity}} token= android.os.BinderProxy@cf28518
08-30 20:39:38.002  1964  3135 I ActivityTaskManager: Background activity start: original ProcessRecord{2ddcf05 18340:com.samsung.android.scan3d/u0a172}is BackgroundActivityStartsAllowed
08-30 20:39:38.018 18340 18340 D MouseWheelSynthesizer: mMoveStepInDp: 64, mMoveStepInPixel: 216, mUpTimeDelayed: 100
08-30 20:39:38.019 18340 18340 D ViewRootImpl: ViewRootImpl mIsInProductivePCDisplay: false
08-30 20:39:38.019 18340 18340 I HwPartPowerOfficeFactory: add HwPartPowerOfficeFactoryImpl to memory.
08-30 20:39:38.022  1964  2159 D HwActivityManagerServiceEx: notifyAppToTop pid:18340, enable:1
08-30 20:39:38.022 18340 18340 I DecorView[]: pkgName:com.samsung.android.scan3d old windowMode:1 new windoMode:1, isFixedSize:false
08-30 20:39:38.025 18340 18340 D InputEventReceiver: dispatchInputInterval 1000000
08-30 20:39:38.027 18340 18340 I RmeSchedManager: init Rme, version is: v1.0
08-30 20:39:38.027 18340 18340 I RtgSchedEvent: current pid:18340 AppType:-1
08-30 20:39:38.043 18340 18383 D HiTouch_PressGestureDetector: onAttached, package=com.samsung.android.scan3d, windowType=1, mIsHiTouchRestricted=false
08-30 20:39:38.052 18340 18380 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-30 20:39:38.057 18340 18380 W Gralloc3: mapper 3.x is not supported
08-30 20:39:38.073 18340 18340 I HwViewRootImpl: removeInvalidNode jank list is null
08-30 20:39:38.075 18340 18340 I CAM     : onStartCommand start
08-30 20:39:38.078  1964  2026 I DebugKeepScreenOn: setHoldScreenLocked newHoldScreen:Session{31764bd 18340:u0a10172} currentHoldScreen:null wakeLockState:false
08-30 20:39:38.092 18340 18340 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
08-30 20:39:38.092 18340 18340 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
08-30 20:39:38.092 18340 18340 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
08-30 20:39:38.116 18340 18340 I PlatformDependent: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
08-30 20:39:38.117 18340 18340 E .android.scan3: No implementation found for int io.netty.channel.kqueue.Native.sizeofKEvent() (tried Java_io_netty_channel_kqueue_Native_sizeofKEvent and Java_io_netty_channel_kqueue_Native_sizeofKEvent__)
08-30 20:39:38.118 18340 18340 E .android.scan3: No implementation found for int io.netty.channel.epoll.Native.offsetofEpollData() (tried Java_io_netty_channel_epoll_Native_offsetofEpollData and Java_io_netty_channel_epoll_Native_offsetofEpollData__)
08-30 20:39:38.127 18340 18340 W .android.scan3d: type=1400 audit(0.0:16679): avc: denied { read } for pid=18340 name="somaxconn" dev="proc" ino=1940257 scontext=u:r:untrusted_app:s0:c172,c256,c512,c768 tcontext=u:object_r:proc_net:s0 tclass=file permissive=0
08-30 20:39:38.156 18340 18340 I CAM     : onStartCommand onResume
08-30 20:39:38.156 18340 18380 D OpenGLRenderer: disableOutlineDraw is true
08-30 20:39:38.156 18340 18340 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-30 20:39:38.156 18340 18340 W InputMethodManager: startInputReason = 1
08-30 20:39:38.157 18340 18340 W HwRemoteInputMethodManager: isCasting false because IHwDistributedWindowManager is invalid.
08-30 20:39:38.158 18340 18340 I CAM     : onStartCommand onPause
08-30 20:39:38.165 18340 18340 D DecorView: showOrHideHighlightView: hasFocus=false; winMode=1; isMrgNull=true
08-30 20:39:38.226 18340 18340 D RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:22, errno:103
08-30 20:39:38.226 18340 18340 D ActivityThread: Won't deliver top position change in state=4
08-30 20:39:38.227 18340 18340 D RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:23, errno:103
08-30 20:39:38.229 18340 18340 D RtgSchedIpcFile: setCommandByIoctl failed ret:-1, cmdid:22, errno:103
08-30 20:39:38.242 18340 18340 I OverScrollerOptimization: start init SmartSlideOverScroller and get the overscroller config
08-30 20:39:38.242 18340 18340 I OverScrollerOptimization: get the overscroller config
08-30 20:39:38.243  1964  2036 D HwGameAssistantController: UPDATE: mCurFgPkg=com.samsung.android.scan3d, mCurFgPid=18340, mIsCurGame=false
08-30 20:39:38.243  1964  2159 D HwActivityManagerServiceEx: notifyAppToTop pid:18340, enable:1
08-30 20:39:38.263 18340 18340 I AwareAppScheduleManager: post cache drawable res id to aware, resId = 17303655, packagename = com.samsung.android.scan3d, cost time = 9153125
08-30 20:39:38.279 18340 18340 I onViewCreated: onViewCreated
08-30 20:39:38.280 18340 18340 I CAMMM   : fragmentCameraBinding.buttonKill androidx.appcompat.widget.AppCompatButton{355389c VFED..C.. ......I. 0,0-0,0 #7f080046 app:id/buttonKill}
08-30 20:39:38.282 18340 18340 I onResume: onResume
08-30 20:39:38.283 18340 18340 I RmeSchedManager: init Rme, version is: v1.0
08-30 20:39:38.283 18340 18340 I RtgSchedEvent: current pid:18340 AppType:-1
08-30 20:39:38.284 18340 18340 D DecorView: showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
08-30 20:39:38.284 18340 18340 W InputMethodManager: startInputReason = 1
08-30 20:39:38.284 18340 18340 W HwRemoteInputMethodManager: isCasting false because IHwDistributedWindowManager is invalid.
08-30 20:39:38.286 18340 18340 I CAM     : onStartCommand onResume
08-30 20:39:38.286 18340 18340 I AUTOFIT : Measured dimensions set: 1080 x 2289
08-30 20:39:38.289 18340 18340 I AUTOFIT : Measured dimensions set: 1080 x 1145
08-30 20:39:38.290 18340 18340 I AUTOFIT : Measured dimensions set: 1080 x 2289
08-30 20:39:38.290 18340 18340 I AUTOFIT : Measured dimensions set: 1080 x 1145
08-30 20:39:38.296 18340 18340 D RenderService: RCS is disable
08-30 20:39:38.302 18340 18340 I CAM     : onStartCommand start_camera_engine
08-30 20:39:38.303 18340 18340 I CameraManagerGlobal: Connecting to camera service
08-30 20:39:38.371 18340 18340 I SELECTOR: id: 1
08-30 20:39:38.372 18340 18340 I CAP     : BACKWARD_COMPATIBLE
08-30 20:39:38.373 18340 18340 I CAP     : MANUAL_POST_PROCESSING
08-30 20:39:38.374 18340 18340 I SELECTOR: id: 2
08-30 20:39:38.376 18340 18340 I CAP     : BACKWARD_COMPATIBLE
08-30 20:39:38.376 18340 18340 I CAP     : MANUAL_POST_PROCESSING
08-30 20:39:38.376 18340 18340 I CAP     : CONSTRAINED_HIGH_SPEED_VIDEO
08-30 20:39:38.377 18340 18340 I SELECTOR: id: 3
08-30 20:39:38.378 18340 18340 I CAP     : BACKWARD_COMPATIBLE
08-30 20:39:38.378 18340 18340 I CAP     : MANUAL_POST_PROCESSING
08-30 20:39:38.379 18340 18340 I SELECTOR: id: 4
08-30 20:39:38.381 18340 18340 I CAP     : BACKWARD_COMPATIBLE
08-30 20:39:38.381 18340 18340 I CAP     : MANUAL_POST_PROCESSING
08-30 20:39:38.381 18340 18340 I SELECTOR: id: 5
08-30 20:39:38.383 18340 18340 I CAP     : BACKWARD_COMPATIBLE
08-30 20:39:38.383 18340 18340 I CAP     : MANUAL_POST_PROCESSING
08-30 20:39:38.389 18340 18340 I CAMERA  : initializeCamera
08-30 20:39:38.392 18340 18340 I CameraManager: open camera: 0, package name: com.samsung.android.scan3d
08-30 20:39:38.393  1000 10011 I CameraService: CameraService::connectDevice E (pid 18340 "com.samsung.android.scan3d", id 0)
08-30 20:39:38.393  1000 10011 I Camera2ClientBase: Camera 0: Opened. Client: com.samsung.android.scan3d (PID 18340, UID 10172)
08-30 20:39:38.411 18340 18371 W Gralloc3: allocator 3.x is not supported
08-30 20:39:38.413 18340 18340 I BlockMonitor: dispatchingThrewException In MainThread
08-30 20:39:38.413 18340 18340 D AndroidRuntime: Shutting down VM
08-30 20:39:38.413 18340 18340 I QarthLog: [PatchStore] createDisableExceptionQarthFile
08-30 20:39:38.413 18340 18340 I QarthLog: [PatchStore] create disable file for com.samsung.android.scan3d uid is 10172
08-30 20:39:38.413 18340 18340 E AndroidRuntime: FATAL EXCEPTION: main
08-30 20:39:38.413 18340 18340 E AndroidRuntime: Process: com.samsung.android.scan3d, PID: 18340
08-30 20:39:38.413 18340 18340 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.samsung.android.scan3d.serv.Cam@3a2c271 with Intent { act=start_camera_engine cmp=com.samsung.android.scan3d/.serv.Cam }: java.lang.NullPointerException
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4971)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.app.ActivityThread.access$3300(ActivityThread.java:260)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2486)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
08-30 20:39:38.413 18340 18340 E AndroidRuntime: Caused by: java.lang.NullPointerException
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at com.samsung.android.scan3d.serv.CamEngine.updateView(CamEngine.kt:310)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at com.samsung.android.scan3d.serv.CamEngine.initializeCamera(CamEngine.kt:296)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at com.samsung.android.scan3d.serv.CamEngine$initializeCamera$1.invokeSuspend(Unknown Source:14)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at com.samsung.android.scan3d.serv.Cam.onStartCommand(Cam.kt:98)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4951)
08-30 20:39:38.413 18340 18340 E AndroidRuntime:        ... 8 more
```

**Comment by ghost** [comment]
App is crashing for me as well

**Comment by aicynide** [comment]
Its very easy to fix, you have to ask Chinese Communist Party to fix it. Its a CCP-based issue

**Comment by e1ke** [comment]
Same for me, Pixel 7a Android 16. Are there any plans on updating this app, @Ruddle ? I like the aspects, that your app is open source and supports OBS on the fly. 

Huge thanks in advance!

**Comment by Progamertoat** [comment]
Also Crashing on a Smasung S24 and a Tab s9 fe +
